### ISSUE TITLE
Move to libp2p?

### ISSUE THREAD

**Issue by alanshaw** [mkg20001/js-libp2p-websocket-star-multi#2]
@jacobheun @vasco-santos any objections?

P.S. the README needs an update - still says `libp2p-websocket-star` (no `-multi`)

**Comment by vasco-santos** [comment]
let's move it!

**Comment by jacobheun** [comment]
No objections, we can move this in.

**Comment by mkg20001** [comment]
Ok, moving :bus: :tada:

**Comment by alanshaw** [comment]
Awesome - would you mind adding @jacobheun as a collaborator on npm? Reduce bus factor ;)

**Comment by mkg20001** [comment]
@alanshaw Added :tada:
